#!/bin/bash

# Traefik Reverse Proxy Installation Script for Docker Swarm
#
# This script automates the deployment of Traefik v3 as a secure reverse proxy
# with automatic HTTPS via Let's Encrypt. It is based on the best practices
# from Docker Swarm Rocks.
#
# It will:
# 1. Prompt for your domain name and email address.
# 2. Prompt for a username and password to secure the Traefik dashboard.
# 3. Create a shared overlay network for Traefik and other services.
# 4. Create the necessary directory and placeholder file for Let's Encrypt certificates.
# 5. Generate a 'traefik.yml' file with your custom configuration.
# 6. Deploy Traefik as a Docker Swarm stack.

# --- Pre-flight Check ---
# Check if the user can run docker commands
if ! docker info > /dev/null 2>&1; then
  echo "Error: Docker is not running or you don't have permission to use it."
  echo "Please ensure you are part of the 'docker' group and have logged out/in again."
  exit 1
fi

# Check if OpenSSL is installed for password hashing
if ! command -v openssl &> /dev/null; then
    echo "Error: 'openssl' is not installed. Please install it with 'sudo apt-get install openssl'."
    exit 1
fi

# --- Configuration ---
NETWORK_NAME="main-proxy"
STACK_NAME="traefik"
COMPOSE_FILE="traefik.yml"
ACME_DIR="/opt/traefik"
ACME_FILE="$ACME_DIR/acme.json"

# --- Interactive Setup ---
echo "### Traefik Configuration Setup ###"
read -p "Enter the domain for the Traefik dashboard (e.g., traefik.yourdomain.com): " TRAEFIK_DOMAIN
read -p "Enter your email address (for Let's Encrypt SSL certificates): " LETSENCRYPT_EMAIL
read -p "Enter a username for the Traefik dashboard: " DASHBOARD_USER
read -sp "Enter a password for the dashboard: " DASHBOARD_PASS
echo
echo "----------------------------------------------------"
echo

# --- Script Execution ---

# 1. Create the common overlay network if it doesn't exist
echo "### Checking for Docker network '$NETWORK_NAME'... ###"
if ! docker network inspect "$NETWORK_NAME" >/dev/null 2>&1; then
  echo "Network '$NETWORK_NAME' not found. Creating it now..."
  docker network create --driver=overlay --attachable "$NETWORK_NAME"
  echo "Network '$NETWORK_NAME' created successfully."
else
  echo "Network '$NETWORK_NAME' already exists."
fi
echo

# 2. Create directory and acme.json for Let's Encrypt
echo "### Setting up storage for Let's Encrypt certificates... ###"
mkdir -p "$ACME_DIR"
if [ ! -f "$ACME_FILE" ]; then
    touch "$ACME_FILE"
    chmod 600 "$ACME_FILE"
    echo "Created empty acme.json with secure permissions."
else
    echo "acme.json already exists."
fi
echo

# 3. Generate hashed password for dashboard authentication
echo "### Generating hashed password for dashboard... ###"
HASHED_PASSWORD=$(openssl passwd -apr1 "$DASHBOARD_PASS")
echo "Password hash generated."
echo

# 4. Create the traefik.yml file
echo "### Creating Docker Compose file: $COMPOSE_FILE... ###"
cat > "$COMPOSE_FILE" <<EOF
# traefik.yml
#
# This file defines the Traefik v3 service for a Docker Swarm environment.
# It is generated by the traefik.sh installation script.

version: '3.8'

services:
  traefik:
    image: traefik:v3.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $ACME_DIR:/etc/traefik/acme
    networks:
      - $NETWORK_NAME
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.email=$LETSENCRYPT_EMAIL"
      - "--certificatesresolvers.myresolver.acme.storage=/etc/traefik/acme/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dashboard.rule=Host(\`$TRAEFIK_DOMAIN\`)"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.routers.dashboard.tls=true"
        - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
        - "traefik.http.routers.dashboard.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.users=$DASHBOARD_USER:$HASHED_PASSWORD"

networks:
  $NETWORK_NAME:
    external: true
EOF
echo "Compose file created."
echo

# 5. Deploy the Traefik stack
echo "### Deploying Traefik stack '$STACK_NAME'... ###"
docker stack deploy -c "$COMPOSE_FILE" "$STACK_NAME"
echo

# --- Final Instructions ---
SERVER_IP=$(hostname -I | awk '{print $1}')
echo "####################################################################"
echo "###            Traefik Deployment Initiated!                     ###"
echo "####################################################################"
echo
echo "IMPORTANT: Make sure your domain '$TRAEFIK_DOMAIN' points to this server's IP: $SERVER_IP"
echo
echo "It may take a minute for the service to be available and for the SSL certificate to be generated."
echo "You can check the status with the command: docker stack ps $STACK_NAME"
echo "You can view logs with the command: docker service logs ${STACK_NAME}_traefik"
echo
echo "Once running, access the Traefik dashboard at:"
echo "https://$TRAEFIK_DOMAIN"
echo
echo "Use the username '$DASHBOARD_USER' and the password you provided."
echo